/*
    Rules for mathematical arithmetic expression
    <expr> → <term> {(+ | -) <term>}
    <term> → <factor> {(* | /) <factor>}
    <factor> → id | int_constant | ( <expr> ) */

/*
    <assignmentstmt> -> identifier = <value>;
    <value> -> identifier | int_literal
*/

#include <stdio.h>
#include <ctype.h>
/* Global declarations */
/* Variables */
int charClass;
char lexeme[100];
char token_list[100][100];
char nextChar;
int lexLen;
int token;
int nextToken;
FILE *in_fp;

/* Function declarations */
int lookup(char ch);
void addChar(void);
void getChar(void);
void getNonBlank(void);
int getNextToken(void);
void expr(void);
void term(void);
void factor(void);
void assignmentstmt(void);

/* Character classes */
#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

/* Token codes */
#define INT_LIT 10
#define IDENT 11
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26
#define SEMICOLON 27

/******************************************************/

/* main driver */
int main(void)
{
    /* Open the input data file and process its contents */
    if ((in_fp = fopen("sample.in", "r")) == NULL)
        printf("ERROR - cannot open sample.in \n");
    else
    {
        getChar();
        if (charClass != EOF)
        {
            getNextToken();

            if (nextToken == ASSIGN_OP)
                assignmentstmt();
            else
                expr();
        }
    }
    return 0;
}

/* expr
Parses strings in the language generated by the rule:
<expr> -> <term> {(+ | -) <term>}
*/
void expr(void)
{
    printf("Enter <expr>\n");
    /* Parse the first term */
    term();
    /* As long as the next token is + or -, get
    the next token and parse the next term */
    while (nextToken == ADD_OP || nextToken == SUB_OP)
    {
        getNextToken();
        term();
    }
    printf("Exit <expr>\n");
}

/* term
Parses strings in the language generated by the rule:
<term> -> <factor> {(* | /) <factor>}
*/
void term(void)
{
    printf("Enter <term>\n");
    /* Parse the first factor */
    factor();
    /* As long as the next token is * or /, get the
    next token and parse the next factor */
    while (nextToken == MULT_OP || nextToken == DIV_OP)
    {
        getNextToken();
        factor();
    }
    printf("Exit <term>\n");
}

/* factor
Parses strings in the language generated by the rule:
<factor> -> id | int_constant | ( <expr> )
*/
void factor(void)
{
    printf("Enter <factor>\n");
    /* Determine which RHS */
    if (nextToken == IDENT || nextToken == INT_LIT)
        /* Get the next token */
        getNextToken();
    /* If the RHS is ( <expr> ), call getNextToken to pass over the
    left parenthesis, call expr, and check for the right
    parenthesis */
    else
    {
        if (nextToken == LEFT_PAREN)
        {
            getNextToken();
            expr();
            if (nextToken == RIGHT_PAREN)
                getNextToken();
            else
                error();
        }
        /* It was not an id, an integer literal, or a left
        parenthesis */
        else
            error();
    }
    printf("Exit <factor>\n");
}

/*Parses strings in the language generated by the rule:
    <assignmentstmt> -> identifier = <value>; */

void assignmentstmt(void)
{
    printf("Enter <assignmentstmt>\n");
    if (nextToken == IDENT)
        getNextToken(); /* Get the next token */
                        /* It was not an identifier*/
    else
        error();
    if (nextToken == ASSIGN_OP)
        getNextToken();
    /* It was not an assignment operator*/
    else
        error();
    value(); /* Parse the value */
    if (nextToken == SEMICOLON)
        getNextToken();
    /* It was not a semicolon */
    else
        error();
    printf("Exit <assignmentstmt>\n");
}

/* value
    Parses strings in the language generated by the rule:
    <value> → identifier | int_literal */

void value(void)
{
    printf("Enter <value>\n");
    /* Determine which RHS */
    if (nextToken == IDENT || nextToken == INT_LIT)
        getNextToken(); /* Get the next token */
    /* It was not an id or an integer literal */
    else
        error();
    printf("Exit <value>\n");
}

/******************************************************/
/* lookup - a function to look up operators and
parentheses and return the token */
int lookup(char ch)
{
    switch (ch)
    {
    case '(':
        addChar();
        nextToken = LEFT_PAREN;
        break;
    case ')':
        addChar();
        nextToken = RIGHT_PAREN;
        break;
    case '+':
        addChar();
        nextToken = ADD_OP;
        break;
    case '-':
        addChar();
        nextToken = SUB_OP;
        break;
    case '*':
        addChar();
        nextToken = MULT_OP;
        break;
    case '/':
        addChar();
        nextToken = DIV_OP;
        break;
    case '=':
        addChar();
        nextToken = ASSIGN_OP;
        break;
    default:
        addChar();
        nextToken = EOF;
        break;
    }
    return nextToken;
}

/******************************************************/
/* addChar - a function to add nextChar to lexeme */
void addChar(void)
{
    if (lexLen <= 98)
    {
        lexeme[lexLen++] = nextChar;
        lexeme[lexLen] = '\0';
    }
    else
        printf("Error - lexeme is too long \n");
}

/******************************************************/
/* getChar - a function to get the next character of
input and determine its character class */

void getChar(void)
{
    if ((nextChar = getc(in_fp)) != EOF)
    {
        if (isalpha(nextChar))
            charClass = LETTER;
        else if (isdigit(nextChar))
            charClass = DIGIT;
        else
            charClass = UNKNOWN;
    }
    else
        charClass = EOF;
}

/******************************************************/
/* getNonBlank - a function to call getChar until it
returns a non-whitespace character */
void getNonBlank(void)
{
    while (isspace(nextChar))
        getChar();
}

/******************************************************/
/* getNextToken - Lexical Analyzer which returns tokens */
int getNextToken(void)
{
    lexLen = 0;
    getNonBlank();
    switch (charClass)
    {

    /* Identifiers */
    case LETTER:
        addChar();
        getChar();
        while (charClass == LETTER || charClass == DIGIT)
        {
            addChar();
            getChar();
        }
        nextToken = IDENT;
        break;

    /* Integer literals */
    case DIGIT:
        addChar();
        getChar();
        while (charClass == DIGIT)
        {
            addChar();
            getChar();
        }
        nextToken = INT_LIT;
        break;

    /* Parentheses and operators */
    case UNKNOWN:
        lookup(nextChar);
        getChar();
        break;

    /* EOF */
    case EOF:
        nextToken = EOF;
        lexeme[0] = 'E';
        lexeme[1] = 'O';
        lexeme[2] = 'F';
        lexeme[3] = '\0';
        break;
    } /* End of switch */
    printf("Next token is: %d, Next lexeme is %s\n",
           nextToken, lexeme);
    return nextToken;
} /* End of function getNextToken */
